[package]
name = "accessor-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[dev-dependencies]
uintx = "0.1"
